THI-CSI/decentralized_iam_battery_data

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This pull request is part of #3.
N/A
@bee1850
=> Issue and Pullrequest Templates

README.md
This pull request is closes issue #10 for the time being.
This needs to be extended and continuously updated in the future. This is supposed to be the initial implementation. 
@TimoGalax
=> Feat#10/readme adjustment

blockchain/cmd/main.go, blockchain/internal/core/block.go
This pull request closes issue (#43).
Two `TODO`s have been added into the code, which are solved with the ticket #48.
@Ampferl
=> Implement basic Block Generation and Validation

blockchain/cmd/main.go, blockchain/internal/api/cli/cli.go
This pull request closes issue #46.
N/A
Felix Wallner
---
=> feat: added skeleton cli

blockchain/.gitignore, blockchain/README.md, blockchain/cmd/main.go, blockchain/internal/api/cli/cli.go, blockchain/internal/core/block.go, blockchain/internal/storage/storage.go
This pull request closes issue (#49).
N/A
@Ampferl 
---
Please assign this issue to the relevant **teams** for review. Add appropriate **labels** and the appropriate **project sprint**.
=> feat: Implement Blockchain Storage Module (#49)

data_gen/data_generator.py, data_gen/test_endpoint.py
This pull request closes issue #73.
First version of the data generation script which sends data to an API endpoint. 
This PR also includes an additional API endpoint script for receiving data and testing.
Patrick Landwehrjohann
=> feat: Add data_gen and test_endpoint script

blockchain/Makefile, blockchain/README.md, blockchain/internal/api/cli/cli.go, blockchain/internal/core/block.go, blockchain/internal/core/transaction.go, blockchain/internal/core/transaction_test.go
This pull request closes issue (#48).
A bug subissue was created since the bulk of this PR should be fine but the TransactionHash creation is inconsistent with a fixed timestamp.
@Fynnwind
=> feat: basic transactions (Transaction Hash inconsistent)

CONTRIBUTING.md
=> Define Contribution Guidelines

requirements/datatypes_attributes.md
This pull request closes issue #90 .
An overview of data attributes and relevant information has been created.
Paulina Mair
---
=> DataTypes_Attributes

README.md, blockchain/.gitignore, blockchain/README.md, blockchain/cmd/main.go, blockchain/frontend/index.html, blockchain/frontend/src/routes/index.tsx, blockchain/go.mod, blockchain/go.sum, blockchain/internal/api/cli/cli.go, blockchain/internal/core/block.go, blockchain/internal/core/chain.go, blockchain/internal/storage/storage.go
This pull request closes issue (#99 #113 #116 #117)
N/A
@Ampferl
=> feat: Blockchain Refactoring and CLI improvements 

cloud/flash.py
This pull request closes issue #93.
The flashing functionality only implements the key generation and registration. Flashing will be done in a separate step.
@valljah
=> feat: Key generation functionality for BMS keys

.github/workflows/build-d2.yml, organizational/diagrams/did_creation.d2, organizational/diagrams/service_access.d2, organizational/diagrams/vc_creation.d2
This pull request closes issue #175  and #149 .
Couldn't test this PR yet, because the action needs to be pushed onto main to make it visible.
Berkan Erkasap and Pascal Esser
---
=> docs: Add d2 action

blockchain/internal/jsonschema/vc.schema.json
This pull request closes issue (-).
Additional relevant notes or context, or write "N/A" if not applicable.
@Fynnwind
=> add 2 different read access Levels

cloud/test_client.py
This pull request closes issue #TBD3 – Implement basic logging for API and retry errors.
- Introduced `logging` module with `INFO`, `WARNING`, and `ERROR` levels
- Logs each retry attempt, HTTP status codes, and exceptions
- Replaced `print()` statements with structured logs
- Helps with debugging API data transfer and stability
- `cloud/test_client.py`
Authored by @ensarozen
=> feat: add logging for retry and API error handling (#TBD3)

cloud/api.py
This pull request enhances the BatteryPass API by adding:
A GET /batterypass/ endpoint to list all DIDs
Automatic timestamp on insert
Logging when duplicate DIDs are submitted
These additions support traceability, diagnostics, and testing without affecting the core encryption or data logic.
Closes #182
PRJ_CSI_REQ_TBD – Improve BatteryPass API with Utility Features (List DIDs, Timestamp, Logging)
[#182]
=> feat: Add DID listing, timestamps and duplicate logging

.github/workflows/build-d2.yml, .github/workflows/build-typst.yml
Reverts THI-CSI/decentralized_iam_battery_data#195
=> Revert "Fix/actions"

bms/Makefile, bms/README.md, bms/configuration.xml, bms/dns-server.conf, bms/src/net_thread_entry.c
This pull request closes issue #147 
Just works under Linux.
@M4tse
=> Routing Gateway for BMS

bms/Makefile, bms/src/net_thread_entry.c
Rewritten cJson for FreeRTOS.
@M4tse
=> Library to create and parse JSON Objects on the BMS

README.md
This pull request closes issue NONE.
Added communitcation protocol and Sequence Diagrams to readme.
Pascal Esser
---
Please assign this issue to the relevant **teams** for review. Add appropriate **labels** and the appropriate **project sprint**.
=> docs: Add single point of truth to readme

blockchain/docker-compose-dev.yml, blockchain/frontend/src/components/header.tsx, blockchain/frontend/src/routes/blocks/index.tsx, blockchain/frontend/src/routes/dids/index.tsx, blockchain/tools.py
This pull request closes issue #217.
Also fixed console.errors in the frontend which was introduced by the PR #189.
@Ampferl @Falo04 
---
=> Fix error handling for docker enviroment and blockchain.json.

bms/README.md
This pull request closes issue #35 
N/A
@M4tse 
---
Please assign this issue to the relevant **teams** for review. Add appropriate **labels** and the appropriate **project sprint**.
=> doc: fixed communication to the docker/podman container

mock_bms/key_gen.py, mock_bms/message_creation.py
for Mock-BMS
This pull request closes issue (#229), (#230).
N/A
@flosmue
=> Message creation process and initial key pair generation for Mock-BMS

README.md
Add python 'requests' requirement installation documentation to the `README.md` file
=> doc: Add python 'requests' requirement installation to the README
